### ISSUE TITLE
masscan usage

### ISSUE THREAD

**Issue by Creative-Difficulty** [Zerogoki00/minescanner#7]
Can you please provide the command you used to get the`example.txt`?
I cannot get this to work!

**Comment by Zerogoki00** [comment]
> Can you please provide the command you used to get the`example.txt`? I cannot get this to work!

Do you mean `example.txt` in `in` or `scanned` dir?

**Comment by Creative-Difficulty** [comment]
Thanks for the quick response!
I just fiddled with it a little bit and got my own version of the `masscan` command to work:
```
# Scan entire American IP range
sudo masscan -iL ipp.txt --rate 100000 -p25565 --exclude 255.255.255.255
#Scan one IP for all ports
sudo masscan <ip> --ports 0-65535 --rate 100
```

my `app.txt` is taken from [this website](https://suip.biz/?act=ipcountry)!

Regards, Alex!
